---
  .travis.yml:
    hc_secure: "Uw6tB4v2ByAo5G03IV3U73qAIfxLxVDSOy4vemHdj0/eyqw79xsS8+vvEQMg2rjSVxonfxzHNycysZpxoJqPZvaWRX6NCGYoxx957xLCIHhNrPetrGadldOOOMvmkuMdQnTssyUr5yGhvj5yLMUqVLLp4RbYvyexBZFGofLhK6M="

