name 'evenup-ct2ls'
version '0.0.1'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Installs a daemon script to import logs from cloudtrail to logstash'
description 'Installs a daemon script to import logs from cloudtrail to logstash'
project_page 'https://github.com/evenup/evenup-ct2-ls'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'evenup/ruby', '>= 1.5.0'

